[workspace]
authors = ["Matt Haberland <mhaberla@calpoly.edu>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

# `normal` package definition 

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.host-dependencies]
uv = "*"

[package.run-dependencies]
scipy = "*"

# environment definitions

[environments]
tests = { features = ["tests"], solve-group = "default" }
lint = { features = ["lint"], solve-group = "default" }
dev = { features = ["tests", "lint", "dev"], solve-group = "default" }

# default feature definition

[dev]
# pulls in host and run dependencies
normal.path = "."

[dependencies]
normal.path = "."

# non-default feature definitions

[feature.tests.dependencies]
pytest = "*"

[feature.tests.tasks.tests]
cmd = "pytest"
default-environment = "tests"

[feature.lint.dependencies]
ruff = "*"
pre-commit = "*"

[feature.lint.tasks.lint]
cmd = "pre-commit run --all-files"
default-environment = "lint"

[feature.dev.dependencies]
pixi-pycharm = "*"
ipython = "*"
python-semantic-release = "*"
