[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"

[project]
name = "normal"
version = "1.0.0"
authors = [{name = "Matt Haberland", email = "matt.haberland@gmail.com"}]
license = "MIT"
license-files = ["LICENSE"]
dependencies = ["scipy"]

[project.urls]
Home = "https://github.com/mdhaber/"

[tool.ruff]
exclude = [".pixi"]

[tool.ruff.lint]
select = ["F", "E", "W", "I"]
preview = true

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
build_command = "uv build"
allow_zero_version = true

[tool.semantic_release.remote]
name = "upstream"
